# Generated by Django 2.2.16 on 2022-03-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220321_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(max_length=150),
        ),
    ]
